const express=require('express')
const db=require('./config/db')
const auth=require('./routes/auth')
const type=require('./routes/type')
const products=require('./routes/product')
const comments=require('./routes/comment')
const err=require('./middleware/error')
const order=require('./routes/order')
const search=require('./routes/search')
const cartdeDt=require('./routes/cartdeDt')
const cart=require('./routes/cart')
const cors = require('cors')
require('dotenv').config()
const app=express()
app.use(cors())
db.connect()
app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use('/auth',auth)
app.use('/search',search)
app.use('/api/type',type)
app.use('/api/cartdt',cartdeDt)
app.use('/api/cart',cart)
app.use('/api/products',products)
app.use('/api/comments',comments)
app.use('/api/order',order)
app.use('/img',express.static('public'))
app.use('/userimg',express.static('public/imguser'))
app.use('/card',express.static('public/card'))
app.use(err.error)
app.use(err.handleError)
module.exports=app