const express=require('express')
const router=express.Router()
const auth=require('../controller/auth')
const verifytokenadmin = require('../middleware/admin')
const verifytoken = require('../middleware/auth')
router.get('/',auth.getAllUser)
router.get('/:id',auth.findone)
router.get('/user/inf',verifytoken,auth.findinf)
router.post('/',auth.searchUser)
router.put('/:id',auth.bantime)
router.put('/infmation/user',verifytoken,auth.uploadImage,auth.updateinformation)
router.put('/banCm/:id',verifytokenadmin,auth.banCm)
router.delete('/:id',verifytokenadmin,auth.deleteUser)
router.get('/ref/acl',auth.verifytoken)
router.post('/register',auth.register)
router.post('/login',auth.login)
module.exports=router